---
- hosts: devserver
  become: yes
  ignore_errors: True
  vars:
    username: alex
    pkg_name: httpd
    item: softwares
  tasks:
    - name: Creating user
      user:
        name: "{{ username }}"
        comment: alex admin
        shell: /bin/bash
        # when: ansible_os_family == "Redhat"
    - name: create file
      file:
        path: /tmp/ansible2.txt
        state: touch
        mode: '0600'
      register: output
    - name: read the output
      debug:
        msg: "Hello from ansible  this is running on {{ ansible_os_family }}"
    - name: create directory
      file:
        path: /tmp/ansible
        state: directory
        mode: '0777'
      tags:
        - app1
        - c1

    - name: installs
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - samba
        - mysql
        - finger
